### ISSUE TITLE
case class with field option[Int] is resolved as object and not Number

### ISSUE THREAD

**Issue by ruioliveiras** [swagger-api/swagger-scala-module#55]
Hi, 
When I have something like this:
> case class  Test(quantity:Int, quantityOpt:Option[Int])

The swagger model will have this properties:
````
    properties:
      quantity:
        type: integer
        format: int32
      quantityOpt:
        type: object
```` 
But the right definition should be something like this
````
    properties:
      quantity:
        type: integer
        format: int32
      quantityOpt:
        type: integer
        format: int32
```` 

@pjfanning , @fehguy

There are any solution for it ?

Thanks !
